jobs:

#####
# Retrieve DOUG
#####
- name: DOUG
  query-name:
      name: DOUG
      field: data

#####
# Retrieve Library Addresses
#####
- name: ErrorsLib
  query-contract:
    destination: $DOUG
    bin: DOUG
    function: lookup
    data: [ErrorsLib]

- name: ArrayUtils
  query-contract:
    destination: $DOUG
    bin: DOUG
    function: lookup
    data: [ArrayUtils]

- name: MappingsLib
  query-contract:
    destination: $DOUG
    bin: DOUG
    function: lookup
    data: [MappingsLib]

#####
# ProcessModel 1.1.0
#####

- name: ProcessModelRepository
  query-contract:
    destination: $DOUG
    bin: DOUG
    function: lookup
    data: [ProcessModelRepository]

- name: ProcessModelInstance
  call:
    destination: $ProcessModelRepository
    bin: ProcessModelRepository
    function: createProcessModel
    data: ["modelID12345abcde", "Model Name", [1,0,0], $defaultAddr, false, "{fileRef}" ]

- name: ProcessModelDelegateBefore
  query-contract:
    destination: $ProcessModelInstance.modelAddress
    bin: ObjectProxy
    function: getDelegate

- name: ProcessModelVersionBefore
  query-contract:
    destination: $ProcessModelDelegateBefore
    bin: ProcessModel
    function: getArtifactVersion

- name: NewProcessModelImplementation
  deploy:
    contract: NewProcessModel.bin
    libraries: ErrorsLib:$ErrorsLib, ArrayUtilsAPI:$ArrayUtils, MappingsLib:$MappingsLib

- name: ObjectClassProcessModel
  query-contract:
    destination: $ProcessModelRepository
    bin: ProcessModelRepository
    function: OBJECT_CLASS_PROCESS_MODEL

- name: RegisterProcessModelObjectClass
  call:
    destination: $DOUG
    bin: DOUG
    function: register
    data: [$ObjectClassProcessModel, $NewProcessModelImplementation]

- name: ProcessModelDelegateAfter
  query-contract:
    destination: $ProcessModelInstance.modelAddress
    bin: ObjectProxy
    function: getDelegate

- name: ProcessModelVersionAfter
  query-contract:
    destination: $ProcessModelDelegateAfter
    bin: ProcessModel
    function: getArtifactVersion

- name: AssertProcessModelDelegateVersion
  assert:
    key: $RegisterProcessModelObjectClass
    relation: eq
    val: $ProcessModelVersionAfter

