jobs:

- name: DOUG
  query-name:
      name: DOUG
      field: data

- name: ErrorsLib
  query-contract:
    destination: $DOUG
    bin: DOUG
    function: lookup
    data: [ErrorsLib]

- name: ArrayUtils
  query-contract:
    destination: $DOUG
    bin: DOUG
    function: lookup
    data: [ArrayUtils]

- name: IsoCountries
  deploy:
    contract: IsoCountries100.bin
    libraries: ErrorsLib:$ErrorsLib

- name: IsoCurrencies
  deploy:
    contract: IsoCurrencies100.bin
    libraries: ErrorsLib:$ErrorsLib
