jobs:

#####
# Retrieve DOUG
#####
- name: DOUG
  query-name:
      name: DOUG
      field: data

#####
# Retrieve Library Addresses
#####
- name: ErrorsLib
  query-contract:
    destination: $DOUG
    bin: DOUG
    function: lookup
    data: [ErrorsLib]

- name: TypeUtils
  query-contract:
    destination: $DOUG
    bin: DOUG
    function: lookup
    data: [TypeUtils]

- name: ArrayUtils
  query-contract:
    destination: $DOUG
    bin: DOUG
    function: lookup
    data: [ArrayUtils]

- name: MappingsLib
  query-contract:
    destination: $DOUG
    bin: DOUG
    function: lookup
    data: [MappingsLib]

- name: BpmRuntimeLib
  query-contract:
    destination: $DOUG
    bin: DOUG
    function: lookup
    data: [BpmRuntimeLib]

- name: DataStorageUtils
  query-contract:
    destination: $DOUG
    bin: DOUG
    function: lookup
    data: [DataStorageUtils]

#####
# Applications
#
# ApplicationTypes Enum: {0=EVENT, 1=SERVICE, 2=WEB}
#####

- name: ApplicationRegistry
  query-contract:
    destination: $DOUG
    bin: DOUG
    function: lookup
    data: [ApplicationRegistry]

- name: AgreementSignatureCheck
  deploy:
    contract: AgreementSignatureCheck.bin
    libraries: ErrorsLib:$ErrorsLib, ArrayUtilsAPI:$ArrayUtils, TypeUtilsAPI:$TypeUtils, MappingsLib:$MappingsLib, DataStorageUtils:$DataStorageUtils

- name: registerApplicationAgreementSignatureCheck
  call:
    destination: $ApplicationRegistry
    bin: ApplicationRegistry
    function: addApplication
    data: ["AgreementSignatureCheck", 2, $AgreementSignatureCheck, "", "SigningWebFormWithSignatureCheck"]

- name: addAgreementSignatureCheckAccessPoint
  call:
    destination: $ApplicationRegistry
    bin: ApplicationRegistry
    function: addAccessPoint
    data: ["AgreementSignatureCheck", "agreement", 59, 0]

# TotalCounterCheck
- name: TotalCounterCheck
  deploy:
    contract: active-agreements/TotalCounterCheck.bin
    libraries: ErrorsLib:$ErrorsLib

- name: registerTotalCounterCheck
  call:
    destination: $ApplicationRegistry
    bin: ApplicationRegistry
    function: addApplication
    data: ["TotalCounterCheck", 1, $TotalCounterCheck, "", ""]

- name: addTotalCounterCheckNumberInAccessPoint
  call:
    destination: $ApplicationRegistry
    bin: ApplicationRegistry
    function: addAccessPoint
    data: ["TotalCounterCheck", "numberIn", 8, 0]

- name: addTotalCounterCheckTotalInAccessPoint
  call:
    destination: $ApplicationRegistry
    bin: ApplicationRegistry
    function: addAccessPoint
    data: ["TotalCounterCheck", "totalIn", 8, 0]

- name: addTotalCounterCheckNumberOutAccessPoint
  call:
    destination: $ApplicationRegistry
    bin: ApplicationRegistry
    function: addAccessPoint
    data: ["TotalCounterCheck", "numberOut", 8, 1]

- name: addTotalCounterCheckCompletedOutAccessPoint
  call:
    destination: $ApplicationRegistry
    bin: ApplicationRegistry
    function: addAccessPoint
    data: ["TotalCounterCheck", "completedOut", 1, 1]
